### ISSUE TITLE
Issue When Using "gulp serve"

### ISSUE THREAD

**Issue by yellowface7** [google/santa-tracker-web#22]
So I was following the setup process to the best of my ability. When I got to the part where I have to use the command "gulp serve" to build and run the repo, my command window spat this out at me: 

https://photos.app.goo.gl/rKEPncswhBRX3zXbA

`fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\Matthew\node_modules\SantaTracker\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Matthew\node_modules\SantaTracker\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Matthew\node_modules\SantaTracker\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)`

I'm relatively new to this repo. Please inform me if more info is needed.

**Comment by samthor** [comment]
Sorry, this is a version from a few years ago and is definitely broken.
We'll open-source the code from 2019 in early 2020—watch this space and the
Google Open-Source blog.

**Comment by yellowface7** [comment]
Ah. This explains a lot. 
Thank you for the explanation. I shall indeed watch this repo closely.
I'm excited for this to open.
